apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: image 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: image 
    spec:
      containers:
        - name: image 
          image: mycontainer1990.azurecr.io/image
          ports:
          - containerPort: 8080